name: Build
on: 
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 13 Pro'
      - run: ls

