name: Build
on: 
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: brew update && brew tap majd/repo && brew install ipatool && ipatool auth login -e dryden@allergist.com -p Lemieux66!
