name: Build
on: 
  push:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: brew update && brew tap majd/repo && brew install ipatool && ipatool auth login --email dryden@allergist.com -p Lemieux66!
      - run: ipatool search --limit 1 TestFlight

